language: ruby
sudo: false

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.4

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.2.4
      gemfile: gemfiles/rails_3_2.gemfile

services:
  - mysql

before_script:
  - mysql -e 'create database ar_transaction_changes_test'
